---
- name: Instalar Docker en los servidores
  hosts: all
  become: true

  tasks:
    - name: Actualizar el sistema
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Instalar dependencias necesarias
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Añadir repositorio de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Añadir repositorio de Docker a sources.list
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Habilitar y arrancar el servicio Docker
      service:
        name: docker
        state: started
        enabled: yes
